"""
wire_fa_into_app.py
===================
One-shot script that wires Farm Auto into app.py as a parallel rendering
branch alongside Business Auto.

Steps performed:
  1. Add FA-specific session-state defaults after the BA defaults.
  2. Add FA helper functions (_fa_valid, n_fa_req, ...) after the BA helpers.
  3. Update the header progress counter so it works for Farm Auto too.
  4. Remove "Farm Auto" from the Coming-Soon dict.
  5. Append a new `elif active_lob == "Farm Auto":` block, generated by
     transforming the existing BA block:
       - Imports rerouted to the FA package.
       - Session-state names prefixed with `fa_` to keep BA / FA isolated.
       - Streamlit widget `key=` values prefixed with `fa_` to avoid collisions.
       - Brand text changed (BA -> FA, Business Auto -> Farm Auto).

Run once.  Re-running is destructive — it would duplicate sections — so
guard rails check that FA is not already wired before applying.
"""
import re
from pathlib import Path

APP = Path(__file__).resolve().parent / "app.py"
text = APP.read_text(encoding="utf-8")

if 'elif active_lob == "Farm Auto":' in text:
    raise SystemExit("FA already wired into app.py — aborting (would duplicate).")

# --------------------------------------------------------------------------
# Session-state names that the BA block reads/writes.  Each one is prefixed
# with `fa_` in the cloned FA block.
# --------------------------------------------------------------------------
SESSION_NAMES = [
    "confirm_step", "mode",
    "multi_gen_pdf", "multi_results", "multi_save_dir",
    "multi_sched_excel", "multi_sched_map", "multi_sched_mode",
    "multi_src_dir", "multi_step",
    "pdf_path", "pdf_status",
    "run_msg", "run_status",
    "save_dir", "sched_mod",
    "upload_reset",
    "xlsx_path",
    # also referenced through f-string subscripts
]

# Streamlit widget keys defined inside the BA block — must be unique across
# branches.  Prefixing with `fa_` avoids collisions if both blocks ever
# render in the same session (currently they don't, but it's free safety).
WIDGET_KEYS = [
    "browse_btn", "browse_save_btn", "browse_src_btn",
    "btn_ind", "btn_mul",
    "cancel_btn",
    "gen_pdf_btn",
    "multi_cancel_btn", "multi_pdf_chk", "multi_proc_btn",
    "multi_proceed_btn", "multi_reset_btn", "multi_run_btn",
    "multi_run_cfm", "multi_run_dis", "multi_save_input",
    "multi_sched_excel_uploader", "multi_sched_mode_radio",
    "multi_src_input",
    "pdf_btn_proc",
    "proceed_btn",
    "run_btn", "run_btn_cfm", "run_btn_dis", "run_btn_proc",
]


# --------------------------------------------------------------------------
# 1) Add FA session defaults right after BA's
# --------------------------------------------------------------------------
fa_defaults = """
# ─── Farm Auto session state (mirrors BA, namespaced with fa_) ───────────────
for k in ALL_KEYS:
    st.session_state.setdefault(f"fa_file_{k}", None)
st.session_state.setdefault("fa_save_dir",    "")
st.session_state.setdefault("fa_sched_mod",   0)
st.session_state.setdefault("fa_run_status",  "idle")
st.session_state.setdefault("fa_run_msg",     "")
st.session_state.setdefault("fa_xlsx_path",   "")
st.session_state.setdefault("fa_pdf_path",    "")
st.session_state.setdefault("fa_pdf_status",  "idle")
st.session_state.setdefault("fa_confirm_step","idle")
st.session_state.setdefault("fa_upload_reset",0)
st.session_state.setdefault("fa_mode",        "individual")
st.session_state.setdefault("fa_multi_src_dir", "")
st.session_state.setdefault("fa_multi_save_dir","")
st.session_state.setdefault("fa_multi_gen_pdf", False)
st.session_state.setdefault("fa_multi_step",    "idle")
st.session_state.setdefault("fa_multi_results", [])
st.session_state.setdefault("fa_multi_sched",      0)
st.session_state.setdefault("fa_multi_sched_map", {})
st.session_state.setdefault("fa_multi_sched_mode", "upload")
st.session_state.setdefault("fa_multi_sched_excel",{})
"""

anchor = 'st.session_state.setdefault("multi_sched_excel",  {})   # raw parsed excel {state: rating}\n'
assert anchor in text, "BA session-state anchor not found"
text = text.replace(anchor, anchor + fa_defaults, 1)


# --------------------------------------------------------------------------
# 2) Add FA helpers after BA's
# --------------------------------------------------------------------------
fa_helpers = """
# Farm Auto helpers — same shape as BA, different session keys
def _fa_valid(k):
    v = st.session_state.get(f"fa_file_{k}")
    return v is not None and "error" not in v

def n_fa_req():     return sum(1 for k in REQUIRED if _fa_valid(k))
def all_fa_req():   return n_fa_req() == len(REQUIRED)
def any_fa_req():   return n_fa_req() > 0
def has_fa_ngic():  return _fa_valid("NGIC")
"""

anchor = "def has_ngic(): return _valid(\"NGIC\")\n"
assert anchor in text, "BA helper anchor not found"
text = text.replace(anchor, anchor + fa_helpers, 1)


# --------------------------------------------------------------------------
# 3) Header progress counter — make it active for Farm Auto too
# --------------------------------------------------------------------------
old_header = '''    with h2:
        if active_lob == "Business Auto":
            nr = n_req(); tot = len(REQUIRED); pct = int(nr/tot*100)'''
new_header = '''    with h2:
        if active_lob in ("Business Auto", "Farm Auto"):
            if active_lob == "Farm Auto":
                nr = n_fa_req()
            else:
                nr = n_req()
            tot = len(REQUIRED); pct = int(nr/tot*100)'''
assert old_header in text, "Header counter anchor not found"
text = text.replace(old_header, new_header, 1)


# --------------------------------------------------------------------------
# 4) Remove Farm Auto from Coming-Soon dict
# --------------------------------------------------------------------------
fa_cs_line = '        "Farm Auto":         ("&#128668;", "Farm Auto",         \'Wire up your FA backend in the <code>elif active_lob == "Farm Auto"</code> block.\'),\n'
assert fa_cs_line in text, "Coming-Soon FA line not found"
text = text.replace(fa_cs_line, "", 1)


# --------------------------------------------------------------------------
# 5) Build the FA block by transforming the BA block
# --------------------------------------------------------------------------
m = re.search(r'(elif active_lob == "Business Auto":.*?)(?=\n# ─── OTHER LOBs)', text, re.DOTALL)
assert m, "BA block not found"
ba_block = m.group(1)

fa_block = ba_block

# 5a. Conditional + comment header
fa_block = fa_block.replace(
    'elif active_lob == "Business Auto":',
    'elif active_lob == "Farm Auto":', 1)

# 5b. Imports — route to FA package
fa_block = fa_block.replace("from BA.BARatePages", "from FA.FARatePages")

# 5c. Brand text in the trailing footer
fa_block = fa_block.replace("BA Analytics Division", "FA Analytics Division")

# 5d. Session-state attribute access:  st.session_state.<NAME>  ->  .fa_<NAME>
for name in SESSION_NAMES:
    fa_block = re.sub(
        r"\bst\.session_state\." + re.escape(name) + r"\b",
        f"st.session_state.fa_{name}",
        fa_block,
    )

# 5e. f-string subscripts: f"file_{...}" -> f"fa_file_{...}"
fa_block = fa_block.replace('f"file_{', 'f"fa_file_{')

# 5f. Widget keys (static): key="X" -> key="fa_X"
for k in WIDGET_KEYS:
    fa_block = re.sub(
        r'(\bkey\s*=\s*)"' + re.escape(k) + r'"',
        r'\1"fa_' + k + '"',
        fa_block,
    )

# 5g. Dynamic widget keys: key=f"multi_up_{...}" -> key=f"fa_multi_up_{...}",
#                         key=f"msm_{...}"     -> key=f"fa_msm_{...}"
fa_block = re.sub(
    r'(\bkey\s*=\s*)f"multi_up_\{',
    r'\1f"fa_multi_up_{',
    fa_block,
)
fa_block = re.sub(
    r'(\bkey\s*=\s*)f"msm_\{',
    r'\1f"fa_msm_{',
    fa_block,
)

# 5h. Tag the new branch with a comment header
fa_block = "# ─── FARM AUTO ───────────────────────────────────────────────────────────────\n" + fa_block

# Insert right before the "Other LOBs" comment block
insert_anchor = "# ─── OTHER LOBs ───"
assert insert_anchor in text, "Other-LOBs anchor not found"
text = text.replace(
    insert_anchor,
    fa_block + "\n\n" + insert_anchor,
    1,
)


# --------------------------------------------------------------------------
# Write back
# --------------------------------------------------------------------------
APP.write_text(text, encoding="utf-8")
print(f"OK — FA wired into {APP}")
print(f"   FA block:        {len(fa_block):,} chars")
print(f"   FA session keys: {len(SESSION_NAMES) + 9}  (file_*, sched, etc.)")
print(f"   FA widget keys:  {len(WIDGET_KEYS) + 2} (incl. 2 dynamic)")
